### ISSUE TITLE
Stateful operations

### ISSUE THREAD

**Issue by thorwhalen** [i2mint/py2dash#7]
**Does py2dash need state management?**

That is, in addition to a bunch of functions to run, there should there be some UI elements to allow to user to manage some stored values, maybe manually edit them, and pass them as arguments to functions?

Well, at some point this will indeed be useful to have.

We start with being able to dispatch a set of functions to a UI. The MVP for that is being able to
(1) allow the user to see and select the functions
(2) enter input
(3) get some output
A lot can be done with such as "stateless" approach.
But for sure, we'd like to then do something to guide the user in specific sequences of actions.

The way I intended to allow DAGs/Pipelines to be implemented in an MVP was to allow outputs to be stored and inputs to be taken from these stored outputs.

Think of the case of a "lite AI platform" where one can upload and prepare data, make and fit learners, and run the resulting models to gather outputs and analyze them.
The datas involved are:
* RAW data
* PREPared Xy data
* LEARNERs (learner class + construction params)
* MODELs (i.e. fitted LEARNERs, i.e. LEARNERS with fit params set)
* MODEL_OUTPUTs (output of MODELs when we feed the X part of (or subset thereof) PREPed data
* MODEL_RESULTs (stats computed -- in the "supervised case -- by comparing MODEL_OUTPUTs from an X, with the y part of the Xy data (from which we took the X)

We have functions:
```
PREP = raw_2_prep(RAW)
LEARNER = mk_learner(params)
MODEL = fit_learner(LEARNER, PREP.X)
MODEL_OUTPUT = run_model(MODEL, PREP.X)
MODEL_RESULT = model_results(MODEL_OUTPUT, PREP.y)
```

All we need is a way to store and retrieve the datas involved.

And py2store will help for this.
In fact even a state-full approach would implement SOME form of such kv stores.
In python, when we say
```
output = func(input)
```
the interpreter is actually doing something like
```
locals['output'] = locals['func'].__call__(locals['input'])
```

So ideally, we can come up with something that will use such a consistent KV crud interface to implement stateful operations, but in such a way that we can easily move from actual disk-persistence to temporary ram assignment on the client side.

**Comment by sylvainbonnot** [comment]
Here is a concrete example where the problem appears: a simple dash app with a FileUpload component allowing the user to upload a zip containing a dataset. Upon uploading, a py2store Store is created from the uploaded zip. That store should be cached since it will be used again and again. What are the best practices to do that in dash?

**Comment by thorwhalen** [comment]
Don't know about "best" practices. 
But my practice is: caching.
For example, [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) with functions whose arguments define the "keys", but `py2store` offers other possibilities in it's caching module, and there's `cachetools` for `lru_cache` kind of functional caches, etc.

**Comment by thorwhalen** [comment]
Most of what is discussed here has been solved by `crude.py`, which is currently part for `front`. 
Linking to [a commit of crude here](https://github.com/i2mint/front/blob/1ebe563c3fe7423faee23f21a4deb1268711cd1c/front/crude.py), in case `crude.py` is moves in the future.

Closing this issue, though other related issues can be found. For example, 
[Complex resolution of element values](https://github.com/i2mint/front/issues/10) 
and
[Scoped access](https://github.com/i2mint/front/issues/6).
